Add non 0 or 5 status code

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -31,7 +31,15 @@ jobs:
       # Run pytest
       - name: Run tests
         if: '!cancelled()'
-        run: pytest
+        run: | 
+          OUTPUT=$(pytest)
+          exit_status=$?
+          if [ $exit_status -ne 0 || $exit_status -ne 5 ]; then
+            echo "Command failed with status $exit_status."
+            exit $exit_status 
+          fi
+          exit 0
+
 
       # Write Pytest overview results to a file
       - name: Record test results
